{% set version = "0.3.0" %}

package:
    name: betamax-matchers
    version: {{ version }}

source:
    fn: betamax-matchers-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/b/betamax-matchers/betamax-matchers-{{ version }}.tar.gz
    md5: 2ca20c328ed9ff8c2b34ff1ceab637c8

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - betamax >=0.3.2
        - requests-toolbelt >=0.4.0

test:
    imports:
        - betamax_matchers

about:
    home: https://github.com/sigmavirus24/betamax_matchers
    license: Apache
    summary: A VCR imitation for python-requests

extra:
    recipe-maintainers:
        - ocefpaf
        - sigmavirus24
