{% set version = "0.3.0" %}

package:
  name: betamax-matchers
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/betamax-matchers/betamax-matchers-{{ version }}.tar.gz
  sha256: 8a2254d94cb5db753e61f95c40f1c2139b2777173dd8c16477746fd634de330d

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - betamax >=0.3.2
    - requests-toolbelt >=0.4.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - betamax_matchers

about:
  home: https://github.com/sigmavirus24/betamax_matchers
  license: Apache
  license_file: LICENSE
  summary: A VCR imitation for python-requests

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
