{% set version = "0.3.0" %}

package:
  name: betamax-matchers
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/betamax-matchers/betamax-matchers-{{ version }}.tar.gz
  sha256: 8a2254d94cb5db753e61f95c40f1c2139b2777173dd8c16477746fd634de330d

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - betamax >=0.3.2
    - requests-toolbelt >=0.4.0

test:
  imports:
    - betamax_matchers

about:
  home: https://github.com/sigmavirus24/betamax_matchers
  license: Apache
  summary: A VCR imitation for python-requests

extra:
  recipe-maintainers:
    - ocefpaf
    - sigmavirus24
