travis:
  secure:
    BINSTAR_TOKEN: PaW9cnGBp4x95/PvJhbLCO/JfviN5Caw48It8dt4aewRnuMqOyImMuCR3keNx+BdG6bNHtEwC/oY62boVVr45kNSYs1d4pCTwvaTAUw89xrc47QWgE6c1zfeRLRgC0ggkgbuLtqP67iABEFhCO8c2qR53fe8nVPSsi+cTDwPydVm26L9jsP2vfK5XpAI3wIj/P8SdC/LQ3Wf2ArNA65cJTPRJPKRESYYUX/g/l7jfMvdCg1/YfSEvHcCtBCYv7V7k21s5I1i85lwpgiM8Oyv7c3owAVRRDJMppiVAWIU2fU1ejA073bOd7ZrSwPEqWECumHVlLfSaEAWN3JbrkuvQA1V5eXdlFFrxDWvrXBRc6Sj+PRfXFY3wYRB8WRTbiqsvDuMbdFJVZL2BxpHz968YOOJidhaWJ/YxAXZMkMJckq6iYm6RjC9vulwp/2rvybOTeBRenYNSc/rWpVMAYCMI0Kxr0NIsCspsi1+yYvCxfX7N4opNOaCA66u2l+eNTFv+pV4azJ8qs//q6aI4uRshJmzgB1yUvbNVn766YPNAKARXf+Vux+id1odxkTHVUzrXk/ruh+9TJjuliBhy+pGxR8JgQCzoIlIC9hK2oMiUfEcYjuqTOtMgEODvqIWZfFKLvcSIADl4rFCqAvYeA8jg5k1vICRqYudrQAzTSwTUWM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
