travis:
  secure:
    BINSTAR_TOKEN: doGyNIV7A59s1Fr9WWYGbqtNot1uaKKjMnGcMT40hIsCZaJPDPiGw8mbY+y/amzgLOtdni2Bsgv3zmD5TfrZwfz0k1APa6mjx2hVdJg2pPQOdTkPD9mxCad/jGdeIJ0JEgwnK9lYAatdjrD67GYNGBaH3BDuoO9aM3EB8Xe9yFAzAxIWOX0v+JT4+JK265fa5FFa+4eg4ORyyBC/jISuJd1uszYN5xLwK2KscIau59A+dLypFHxPJhJJOaJ4PpqGD1RlL8JKJU4bpB5HQjJJN3cngBy7SaOE9qWUz+nF6UnOdRJX4dUHNbtEysOCgn1WEq9VW0g+PABIKB1GnowwkdKh6hdIdVtmKqiaCkkS61X9T8OsWnG8qOJXA8Y/asTAqezlc1sc9Q4aqUwhWneI+YExbuW5ZvlXbkOud1Ye7C1evBDmdIsRkKg29vw8Fl2mC09OnaVSgjicL/imfTg7L3Xb3MROWLzcBszUhRXWnrj7Xcch3ig2PbvaTgl11mefA1Wny44zRpHzcnO0sI8Qq4iCC7Z1Mp5CrJTHj8IOdwYeUu2/YgWJsONYngqwwRYQ5DnSorOTj2lzo9Baho9+EJfiJJ6wEA8CrMVU487fbX20HSbFOXz98kZcGK8vlwRw8DwOi8uKbwKG4yquCoAToAOelsk1tLEiKoihSetlEUg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
